  - name: enable glusterfs services
    systemd:
      name: "{{ item }}" 
      enabled: yes
      state: restarted
    become: true
    with_items: 
        - glusterd
        - glusterfsd
        - glusterfssharedstorage

  - name: create /glustervolumes directory for holding bricks
    file: 
        path: /glustervolumes
        state: directory
    become: true

  - name: gluster peer probe 
    shell: "gluster peer probe {{ item }}"
    become: true
    when: item != inventory_hostname
    with_items:
        - uno
        - dos
        - tres
        - cuatro

  - name: gluster peer status 
    shell: "gluster peer status"
    become: true

        
  - name: create mount point /glustermount
    file:
        name: /glustermount
        state: directory
    become: true

  - name: force unmount of /glustermount
    mount:
        path: /glustermount
        state: unmounted 
    become: true

  - name: mount /glustermount
    mount:
        path: /glustermount
        src: "{{ inventory_hostname }}:/testvol"
        fstype: glusterfs
        state: mounted
    become: true


    
