---
- hosts: all
  remote_user: bootstrap
  gather_facts: yes

  vars:
    packages: { "libselinux-utils", "tcpdump", "git", "ntp", "psmisc", "net-tools", "libselinux-python", "which", "gcc-c++", "keepalived", "haproxy", "bind", "bind-utils", "ccache",
                "fortune-mod", "frotz", "lrzsz", "ii", "epic", "BitchX", "mailx", "postfix", "net-snmp", "net-snmp-utils", "mlocate", "telnet",
                "postfix-perl-scripts", "rsyslog", "httpd", "openldap", "openldap-clients", "openldap-servers", "nodejs", "golang", "monit", "lsof",
                "rpm-build", "mc", "python-dnf", "selinux-policy", "setools-console", "policycoreutils-python-utils", "policycoreutils-devel", "python3-firewall",
                "python-firewall", "kernel", "kernel-core", "kernel-modules", "glibc-static", "libstdc++-static", "django", "kubernetes", "kubernetes-kubeadm", "SDL2-devel", "libpng-devel",
                "glusterfs-server", "glusterfs-client", "java-1.8.0-openjdk" }

    firewall_ports: { "23/tcp", "24/tcp", "25/tcp", "53/udp", "53/tcp", "80/tcp", "2375/tcp", "2812/tcp", "8024/tcp", "8080/tcp",
                      "111/tcp", "24007/tcp", "24008/tcp", "24009/tcp", "24010/tcp", "49152/tcp", "49153/tcp" }
    monit_local: { "sshd", "postfix", "named", "haproxy", "bbsd", "docker", "httpd" }
    monit_remote: { "uno", "dos", "tres", "cuatro" }

  vars_prompt:
    - name: "ansible_password"
      prompt: "Enter password for bootstrap user"
      hidden: yes

  tasks:

  - include: activities/hostbase.yml
  - include: activities/selinux.yml
  - include: activities/disk-resize.yml

  - name: install prerequisite packages
    dnf:
      name: "{{ item }}"
      state: present
    with_items: "{{ packages }}"
    become: true
    tags:
      - installpackages
      - ntpd

  - include: activities/rsyslog.yml

  - name: configure firewall ports
    firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled
      immediate: true
    with_items: "{{ firewall_ports }}"
    become: true
    tags:
      - firewall

  - name: enable NetworkManager-wait-online.service
    systemd:
      name: NetworkManager-wait-online
      enabled: yes
      state: restarted
    become: true
    tags:
      - named
      - networkmanager-wait-online

  - include: roles/docker.yml
  - include: roles/monit.yml
  - include: roles/named.yml
  - include: roles/postfix.yml
  - include: roles/bbsd.yml
  - include: roles/httpd.yml
  - include: roles/haproxy.yml
  - include: roles/keepalived.yml
  - include: roles/elkstack.yml
    tags:
        - elkstack

  # experimental 4-way glusterfs volume
  
  - include: activities/glusterconfig.yml
    tags:
        - glusterconfig 

  # LOL apparently the builtin ansible support for this doesn't work

  - name: install security updates
    shell: dnf -y update --security
    become: true
