---
- hosts: all 
  remote_user: bootstrap 
  gather_facts: no

  vars:
    packages: { "git", "psmisc", "net-tools", "libselinux-python", "which", "gcc-c++", "keepalived", "ccache" }

  vars_prompt:
    - name: "ansible_password"
      prompt: "Enter password for bootstrap user" 
      hidden: yes

  tasks:
  - name: set hostname permanently 
    shell: "/usr/bin/hostnamectl set-hostname {{ inventory_hostname }}"
    become: true

  - name: display hostname 
    shell: /usr/bin/hostname -f

  - name: set selinux to permissive
    shell: /sbin/setenforce 0
    become: true

  - name: install /etc/hosts file
    copy:
      dest: /etc/hosts
      src: files/etc/hosts
      owner: root
      group: root
      mode: 0o644 
    become: true


  - name: install /etc/dnf/dnf.conf file
    copy:
      dest: /etc/dnf/dnf.conf
      src: files/etc/dnf/dnf.conf
      owner: root
      group: root
      mode: 0o644 
    become: true

  - name: install prerequisite packages
    dnf: 
      name: "{{ item }}"
      state: present
    with_items: "{{ packages }}"
    become: true
    tags:
      - installpackages

  - name: create ~/git-local/bbsd
    file:
      dest: ~/git-local/bbsd 
      state: directory
      recurse: true

  - name: checkout bbsd sources to ~/git-local/bbsd
    git:
      repo: 'https://github.com/dmo9000/bbsd.git'
      dest: ~/git-local/bbsd

  - name: build bbsd sources
    shell: "(cd ~/git-local/bbsd && make)"

  - name: install bbbsd 
    shell: "(cd ~/git-local/bbsd && make install)"
    become: true


