---
- hosts: all
  remote_user: bootstrap
  gather_facts: no

  vars_prompt:
    - name: "ansible_password"
      prompt: "Enter password for bootstrap user"
      hidden: yes

  tasks:
  - name: reboot nodes
    shell: /sbin/init 0
    become: true
    ignore_errors: true

  - name: ping till down
    shell: ping "{{ inventory_hostname }}"
    delegate_to: localhost

