  - name: install docker
    dnf:
      name: docker
      state: present
    become: true
    tags:
      - installpackages
      - docker

  - name: add docker group
    group:
      name: docker
      gid: 10000
    become: true
    tags:
      - docker

  - name: adding user bootstrap to docker group
    user:
      name: bootstrap
      groups: docker
      append: yes
    become: true
    tags:
      - docker

  - name: set docker OPTIONS in /etc/sysconfig/docker 
    lineinfile:
      path: /etc/sysconfig/docker
      regexp: '^OPTIONS=.*$'
      line: "OPTIONS='--selinux-enabled --log-driver=journald --live-restore -H=tcp://0.0.0.0:2375 -H=unix:///var/run/docker.sock'"
    become: true
    tags:
      - docker 

  # LOL @ systemd

  - name: start & enable docker on boot
    systemd:
      name: docker
      state: restarted
      enabled: yes
      daemon_reload: yes
    become: true
    tags:
      - docker

  - name: run docker hello-world
    shell: docker run hello-world
    tags:
      - docker

