  - name: install docker
    dnf:
      name: docker
      state: present
    become: true
    tags:
      - installpackages
      - docker

  - name: add docker group
    group: 
      name: docker
      gid: 10000
    become: true
    tags:
      - docker      

  - name: adding user bootstrap to docker group  
    user: 
      name: bootstrap
      groups: docker
      append: yes
    become: true
    tags:
      - docker      

  - name: install /usr/lib/systemd/system/docker.service file
    copy:
      dest: /usr/lib/systemd/system/docker.service
      src: files/usr/lib/systemd/system/docker.service
      owner: root
      group: root
      mode: 0o644
    become: true
    tags:
      - docker      

  # LOL @ systemd

  - name: start & enable docker on boot
    systemd:
      name: docker
      state: restarted
      enabled: yes
      daemon_reload: yes
    become: true
    tags:
      - docker      

  - name: run docker hello-world
    shell: docker run hello-world
    tags:
      - docker      

