  - name: install docker
    dnf:
      name: docker
      state: present
    become: true
    tags:
      - installpackages
      - docker

  - name: install /usr/lib/systemd/system/docker.service file
    copy:
      dest: /usr/lib/systemd/system/docker.service
      src: files/usr/lib/systemd/system/docker.service
      owner: root
      group: root
      mode: 0o644
    become: true
    tags:
      - docker      

  # LOL @ systemd

#  - name: systemd daemon reload
#    shell: /bin/systemctl daemon-reload
#    become: true
#    tags:
#      - docker

  - name: start & enable docker on boot
    systemd:
      name: docker
      state: restarted
      enabled: yes
      daemon_reload: yes
    become: true
    tags:
      - docker      