  - name: install elkstack repo file
    copy: 
        src: files/etc/yum.repos.d/elkstack.repo
        dest: /etc/yum.repos.d/elkstack.repo
        owner: root
        group: root
        mode: 0o644
    become: true

  - name: install elasticsearch 6
    dnf:
      name: elasticsearch 
      state: present
    become: true

  - name: install logstash 
    dnf:
      name: logstash
      state: present
    become: true

