  - name: install elkstack repo file
    file: 
        path: /etc/yum.repos.d/elkstack.repo
        state: absent
    become: true
    tags:
      - elkstack

  - name: remove stupid packages that don't work
    dnf:
      name: elasticsearch logstash kibana 
      state: absent 
    become: true
    tags:
      - elkstack

  - name: set elasticsearch ES_JAVA_OPTS in /etc/sysconfig/elasticsearch
    file:
      path: /etc/sysconfig/elasticsearch
      state: absent
    become: true
    tags:
      - elkstack 


